export type BeachEventProviderMode = "enabled" | "monitorOnly" | "disabled" | "manualOnly";

export interface BeachEventProvider {
	id: string;
	name: string;
	feedURL: string;
	feedType: "iCalendar" | "Google iCalendar" | "RSS" | "JSON" | "Web page" | "Manual";
	mode: BeachEventProviderMode;
	controlId?: "gulfShoresEvents" | "orangeBeachEvents" | "gulfStateParkEvents" | "orangeBeachCoastalEvents";
	authority: string;
	authorityLevel: "official" | "authorized" | "organization";
	publicFeed: boolean;
	automatedRetrieval: "intended" | "unclear" | "not-applicable";
	attribution: string;
	cadence: string;
	caching: string;
	legalStatus: "clear" | "unclear" | "permission-required";
	coverage: string[];
	supportedBeachIds: string[];
	notes: string;
}

export const BEACH_EVENT_PROVIDERS: BeachEventProvider[] = [
	{
		id: "gulfShoresCity",
		name: "City of Gulf Shores Special Events",
		feedURL: "https://www.gulfshoresal.gov/common/modules/iCalendar/iCalendar.aspx?catID=44&feed=calendar",
		feedType: "iCalendar",
		mode: "enabled",
		controlId: "gulfShoresEvents",
		authority: "Official City of Gulf Shores",
		authorityLevel: "official",
		publicFeed: true,
		automatedRetrieval: "intended",
		attribution: "Display the City of Gulf Shores source name and official event URL.",
		cadence: "Daily at 7:00 AM Central",
		caching: "Normalized facts and review records; public snapshot retained for no more than 12 hours.",
		legalStatus: "clear",
		coverage: ["Gulf Shores"],
		supportedBeachIds: ["gulf-shores-public-beach", "little-lagoon-pass"],
		notes: "Official CivicEngage subscription feed. Only exact approved beach venues are retained.",
	},
	{
		id: "orangeBeachParks",
		name: "City of Orange Beach Parks and Recreation",
		feedURL: "https://www.orangebeachal.gov/common/modules/iCalendar/iCalendar.aspx?catID=34&feed=calendar",
		feedType: "iCalendar",
		mode: "enabled",
		controlId: "orangeBeachEvents",
		authority: "Official City of Orange Beach",
		authorityLevel: "official",
		publicFeed: true,
		automatedRetrieval: "intended",
		attribution: "Display the City of Orange Beach source name and official event URL.",
		cadence: "Daily at 7:00 AM Central",
		caching: "Normalized facts and review records; public snapshot retained for no more than 12 hours.",
		legalStatus: "clear",
		coverage: ["Orange Beach"],
		supportedBeachIds: ["cotton-bayou", "alabama-point", "florida-point"],
		notes: "Official CivicEngage Parks and Recreation subscription feed. Inland and citywide entries are rejected.",
	},
	{
		id: "orangeBeachCoastalResources",
		name: "City of Orange Beach Coastal Resources",
		feedURL: "https://orangebeachal.gov/common/modules/iCalendar/iCalendar.aspx?catID=26&feed=calendar",
		feedType: "iCalendar",
		mode: "enabled",
		controlId: "orangeBeachCoastalEvents",
		authority: "Official City of Orange Beach",
		authorityLevel: "official",
		publicFeed: true,
		automatedRetrieval: "intended",
		attribution: "Display Orange Beach Coastal Resources and the official event URL.",
		cadence: "Daily at 7:00 AM Central",
		caching: "Normalized facts and review records; public snapshot retained for no more than 12 hours.",
		legalStatus: "clear",
		coverage: ["Orange Beach coastal-resource programs"],
		supportedBeachIds: ["cotton-bayou", "alabama-point", "florida-point"],
		notes: "Distinct official CivicEngage subscription category. Broad cleanup zones and inland programs remain excluded.",
	},
	{
		id: "gulfStatePark",
		name: "Gulf State Park Events",
		feedURL: "https://calendar.google.com/calendar/ical/2ehkep97u1rsqsgd2cipa7r3ag%40group.calendar.google.com/public/basic.ics",
		feedType: "Google iCalendar",
		mode: "enabled",
		controlId: "gulfStateParkEvents",
		authority: "Official Alabama State Parks",
		authorityLevel: "official",
		publicFeed: true,
		automatedRetrieval: "intended",
		attribution: "Display Gulf State Park and link to the official activities calendar or event URL.",
		cadence: "Daily at 7:00 AM Central",
		caching: "Normalized facts and review records only; no source photographs or descriptions are republished.",
		legalStatus: "clear",
		coverage: ["Gulf State Park Beach Pavilion"],
		supportedBeachIds: ["gulf-state-park-pavilion"],
		notes: "Public Google Calendar embedded by Alabama State Parks. Exact official Pier aliases map to Pavilion for nearby visitor impact; Nature Center, Learning Campus, campground, lake, and trail locations remain excluded.",
	},
	{
		id: "dauphinIslandTown",
		name: "Town of Dauphin Island Events",
		feedURL: "https://www.townofdauphinisland.org/calendar-of-events",
		feedType: "Web page",
		mode: "manualOnly",
		authority: "Official Town of Dauphin Island",
		authorityLevel: "official",
		publicFeed: false,
		automatedRetrieval: "unclear",
		attribution: "Town of Dauphin Island attribution required.",
		cadence: "Manual review",
		caching: "Manual factual records only.",
		legalStatus: "unclear",
		coverage: ["Dauphin Island"],
		supportedBeachIds: ["dauphin-island-public-beach", "dauphin-island-east-end"],
		notes: "The official Wix page does not expose a verified Town-owned structured feed. Island-wide events must never imply a beach match.",
	},
	{
		id: "alabamaCoastalCleanup",
		name: "Alabama Coastal Cleanup",
		feedURL: "https://alabamacoastalcleanup.com/cleanupzones/",
		feedType: "Web page",
		mode: "manualOnly",
		authority: "ADCNR State Lands Division and Alabama PALS",
		authorityLevel: "official",
		publicFeed: false,
		automatedRetrieval: "unclear",
		attribution: "Attribute Alabama Coastal Cleanup and retain the official zone URL.",
		cadence: "Annual manual review",
		caching: "Store limited factual zone, meeting-location, time, and organizer metadata.",
		legalStatus: "unclear",
		coverage: ["Coastal Alabama cleanup zones"],
		supportedBeachIds: ["gulf-shores-public-beach", "cotton-bayou", "gulf-state-park-pavilion", "fort-morgan-public-beach", "dauphin-island-public-beach", "dauphin-island-east-end"],
		notes: "The official site publishes zone facts but no verified event feed. Use the strong manual workflow until an authorized structured source is provided.",
	},
	{
		id: "alabamaAudubon",
		name: "Alabama Audubon Events",
		feedURL: "https://alaudubon.org/event?format=rss",
		feedType: "RSS",
		mode: "disabled",
		authority: "Alabama Audubon",
		authorityLevel: "organization",
		publicFeed: true,
		automatedRetrieval: "intended",
		attribution: "Attribute Alabama Audubon and link to the event page.",
		cadence: "Not automated",
		caching: "No automated caching while disabled.",
		legalStatus: "unclear",
		coverage: ["Coastal conservation and birding"],
		supportedBeachIds: ["fort-morgan-public-beach", "dauphin-island-public-beach", "dauphin-island-east-end", "alabama-point"],
		notes: "A public RSS collection exists, but commercial-app reuse is not explicit and many coastal events occur at unsupported sanctuaries or historic sites. Permission is required before enabling.",
	},
	{
		id: "dauphinIslandSeaLab",
		name: "Dauphin Island Sea Lab Events",
		feedURL: "https://www.disl.edu/events/",
		feedType: "Web page",
		mode: "manualOnly",
		authority: "Dauphin Island Sea Lab",
		authorityLevel: "official",
		publicFeed: false,
		automatedRetrieval: "unclear",
		attribution: "Attribute Dauphin Island Sea Lab and link to the official program.",
		cadence: "Manual review",
		caching: "Manual factual records only.",
		legalStatus: "unclear",
		coverage: ["Dauphin Island education and conservation"],
		supportedBeachIds: ["dauphin-island-public-beach", "dauphin-island-east-end"],
		notes: "No verified structured events feed. Campus, aquarium, vessel, lab, and building programs are not beach events; a program needs an explicit supported beach or admin assignment.",
	},
	{
		id: "fortMorganOfficial",
		name: "Fort Morgan Official Announcements",
		feedURL: "https://ahc.alabama.gov/properties/fortmorgan/fortmorgan.aspx",
		feedType: "Manual",
		mode: "manualOnly",
		authority: "Alabama Historical Commission",
		authorityLevel: "official",
		publicFeed: false,
		automatedRetrieval: "not-applicable",
		attribution: "Attribute the issuing public agency.",
		cadence: "Manual review",
		caching: "Manual factual records only.",
		legalStatus: "clear",
		coverage: ["Fort Morgan area"],
		supportedBeachIds: ["fort-morgan-public-beach"],
		notes: "No reliable beach-specific structured source was verified. Historic site, museum, ferry, campground, and bird-banding events do not map to the public beach.",
	},
	{
		id: "tourismCalendar",
		name: "Gulf Shores & Orange Beach Tourism Calendar",
		feedURL: "https://www.gulfshores.com/events-calendar/",
		feedType: "Web page",
		mode: "disabled",
		authority: "Gulf Shores & Orange Beach Tourism",
		authorityLevel: "organization",
		publicFeed: false,
		automatedRetrieval: "unclear",
		attribution: "Not applicable while disabled.",
		cadence: "Not automated",
		caching: "No automated caching.",
		legalStatus: "permission-required",
		coverage: ["Regional tourism events"],
		supportedBeachIds: [],
		notes: "Permission required. Scraping, undocumented endpoints, copied descriptions, photographs, logos, and deep links remain prohibited.",
	},
];
