export interface Env {
	BEACH_DATA: KVNamespace;
	/** Optional until the historical D1 database is provisioned and migrated. */
	HISTORICAL_DATA?: D1Database;
	HISTORICAL_DATA_ENVIRONMENT?: "staging" | "production";
	REFRESH_COORDINATOR: DurableObjectNamespace;
	VERIFICATION_COORDINATOR: DurableObjectNamespace;
	REFRESH_SECRET: string;
	ALLOW_LEGACY_REFRESH_SECRET?: string;
	ACCESS_TEAM_DOMAIN?: string;
	ACCESS_AUD?: string;
	ACCESS_ALLOWED_IDENTITIES?: string;
	ACCESS_ALLOWED_GROUPS?: string;
	ACCESS_ALLOWED_SERVICE_TOKENS?: string;
	VERIFICATION_API_BASE_URL: string;
	VERIFICATION_ALERTS_ENABLED?: string;
	VERIFICATION_ALERT_ENVIRONMENT: "staging" | "production";
	VERIFICATION_ALERT_EMAIL?: SendEmail;
	AI: Ai;
	BEACH_ACTIVITY_NOTIFICATIONS_ENABLED?: string;
	BEACH_ACTIVITY_NOTIFICATION_RECIPIENTS?: string;
	PROVIDER_HEALTH_NOTIFICATIONS_ENABLED?: string;
	PROVIDER_HEALTH_NOTIFICATION_RECIPIENTS?: string;
	VIBRIO_CONDITIONS_ENABLED?: string;
	IOS_1_2_DOUBLE_RED_COMPATIBILITY?: string;

	WEATHERKIT_TEAM_ID: string;
	WEATHERKIT_KEY_ID: string;
	WEATHERKIT_PRIVATE_KEY: string;
	WEATHERKIT_SERVICE_ID: string;
}
