export interface Env {
	APP_ENVIRONMENT?: "staging" | "production";
	STAGING_LIVE_PROVIDER_FETCH_ENABLED?: string;
	STAGING_EXTERNAL_EMAIL_ENABLED?: string;
	STAGING_SYNTHETIC_FIXTURES_ENABLED?: string;
	BEACH_DATA: KVNamespace;
	/** Optional until the historical D1 database is provisioned and migrated. */
	HISTORICAL_DATA?: D1Database;
	HISTORICAL_DATA_ENVIRONMENT?: "staging" | "production";
	REFRESH_COORDINATOR: DurableObjectNamespace;
	VERIFICATION_COORDINATOR: DurableObjectNamespace;
	REFRESH_SECRET: string;
	ALLOW_LEGACY_REFRESH_SECRET?: string;
	ACCESS_TEAM_DOMAIN?: string;
	ACCESS_AUD?: string;
	ACCESS_ALLOWED_IDENTITIES?: string;
	ACCESS_ALLOWED_GROUPS?: string;
	ACCESS_ALLOWED_SERVICE_TOKENS?: string;
	VERIFICATION_API_BASE_URL: string;
	VERIFICATION_ALERTS_ENABLED?: string;
	VERIFICATION_ALERT_ENVIRONMENT: "staging" | "production";
	VERIFICATION_ALERT_EMAIL?: SendEmail;
	AI: Ai;
	BEACH_ACTIVITY_NOTIFICATIONS_ENABLED?: string;
	BEACH_ACTIVITY_NOTIFICATION_RECIPIENTS?: string;
	/** Canonical protected admin page used in information-report notification links. */
	INFORMATION_REPORTS_ADMIN_URL?: string;
	PROVIDER_HEALTH_NOTIFICATIONS_ENABLED?: string;
	PROVIDER_HEALTH_NOTIFICATION_RECIPIENTS?: string;
	VIBRIO_CONDITIONS_ENABLED?: string;
	IPAWS_INGESTION_ENABLED?: string;
	IPAWS_ENVIRONMENT?: "staging" | "production";
	IPAWS_ALLOWED_TOPIC_ARNS?: string;
	IPAWS_AUTO_CONFIRM_SUBSCRIPTION?: string;
	IPAWS_PARSE_BYTE_LIMIT?: string;
	IPAWS_RECORD_TTL_SECONDS?: string;
	IPAWS_SUBSCRIPTION_TTL_SECONDS?: string;
	IPAWS_HEALTH_TTL_SECONDS?: string;
	IOS_1_2_DOUBLE_RED_COMPATIBILITY?: string;

	WEATHERKIT_TEAM_ID: string;
	WEATHERKIT_KEY_ID: string;
	WEATHERKIT_PRIVATE_KEY: string;
	WEATHERKIT_SERVICE_ID: string;
}
